apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-panel       # mesmo nome usado em k8s_service_account
  namespace: default      # ou o namespace que preferir
  annotations:
    iam.gke.io/gcp-service-account: admin-uploader@devops-challenge-493713.iam.gserviceaccount.com