name: CI/CD Pipeline

on:
  push:
    branches: [ develop ] # Dispara apenas na develop por enquanto

jobs:
  devsecops-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      # 1. SEGURANÇA: Rodar o Checkov para validar o Terraform
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
          framework: terraform
          soft_fail: true # Não para a esteira se houver avisos, apenas avisa

      # 2. AUTENTICAÇÃO: Logar no Google Cloud
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3. TERRAFORM: Planejar as mudanças
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform/