name: CI/CD Pipeline

on:
  push:
    branches: [ develop ]

jobs:
  terraform-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [network, storage_cdn, gke, workload_identity]

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ matrix.folder }}
          framework: terraform
          soft_fail: true

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ${{ matrix.folder }}

      - name: Terraform Plan
        run: terraform plan -input=false -no-color -var-file="terraform.tfvars"
        working-directory: ${{ matrix.folder }}